#include "talos_io.h"
#include "vx_limits.h"
#include "vx_string.h"

#include <stdio.h>
#include <inttypes.h>

bool talos_disk_read(talos_disk_io *io, const char *target_dev)
{
    if (io == nullptr || target_dev == nullptr)
        return false;

    FILE *fp = fopen("/proc/diskstats", "r");
    if (fp == nullptr)
    {
        return false;
    }

    char line[VX_BUF_SIZE_256];
    u64  read_sectors  = 0;
    u64  write_sectors = 0;
    bool found         = false;

    while (fgets(line, sizeof(line), fp))
    {
        char dev_name[32];

        i32 fields = sscanf(line,
                            "%*u %*u %31s %*u %*u %" SCNu64 " %*u %*u %*u %" SCNu64,
                            dev_name,
                            &read_sectors,
                            &write_sectors);

        if (fields == 3 && strcmp(dev_name, target_dev) == 0)
        {
            found = true;
            break;
        }
    }
    fclose(fp);

    if (found)
    {
        if (io->last_read_sectors > 0)
        {
            u64 delta_read  = read_sectors - io->last_read_sectors;
            u64 delta_write = write_sectors - io->last_write_sectors;

            io->read_mb_sec  = (f32) (delta_read * 512) / 1048576.0f;
            io->write_mb_sec = (f32) (delta_write * 512) / 1048576.0f;
        }

        io->last_read_sectors  = read_sectors;
        io->last_write_sectors = write_sectors;
    }

    return found;
}

bool talos_net_read(talos_net_io *net, const char *target_iface)
{
    if (net == nullptr || target_iface == nullptr)
        return false;

    FILE *fp = fopen("/proc/net/dev", "r");
    if (fp == nullptr)
        return false;

    char line[256];
    u64  rx_bytes = 0;
    u64  tx_bytes = 0;
    bool found    = false;

    // Skip the 2 header lines generated by kernel formatting output
    if (fgets(line, sizeof(line), fp))
    {
    }
    if (fgets(line, sizeof(line), fp))
    {
    }

    while (fgets(line, sizeof(line), fp))
    {
        char iface_name[32];
        // Format layout strips name, grabs absolute counters sequentially
        i32 fields = sscanf(line,
                            " %31[^:]:%" SCNu64 " %*u %*u %*u %*u %*u %*u %*u %" SCNu64,
                            iface_name,
                            &rx_bytes,
                            &tx_bytes);

        if (fields == 3 && strcmp(iface_name, target_iface) == 0)
        {
            found = true;
            break;
        }
    }
    fclose(fp);

    if (found)
    {
        if (net->last_rx_bytes > 0)
        {
            u64 delta_rx = rx_bytes - net->last_rx_bytes;
            u64 delta_tx = tx_bytes - net->last_tx_bytes;

            net->rx_kb_sec = (f32) delta_rx / 1024.0f;
            net->tx_kb_sec = (f32) delta_tx / 1024.0f;
        }

        net->last_rx_bytes = rx_bytes;
        net->last_tx_bytes = tx_bytes;
    }

    return found;
}
